spring:
  security:
    oauth2:
      client:   
        registration:
          on-prem-auth-server-cc:
            authorization-grant-type: client_credentials
            client-id: wamya-mobile-app
            client-secret: S3CR3T
            provider: on-prem-auth-server
        
        provider:
          on-prem-auth-server:
            token-uri: "http://${app.auth-server}:9999/oauth/token"
            authorization-uri: "http://${app.auth-server}:9999/oauth/authorize"
            jwk-set-uri: "http://${app.auth-server}:9999/.well-known/jwks.json"

app:
  auth-server: auth-server 
  oauth2:
    client-credentials-registration-id: client-credentials-on-prem-auth-server
    password-registration-id: password-on-prem-auth-server
    create-user-uri: "http://${app.auth-server}:9999/oauth/users"
    token-uri: "http://${app.auth-server}:9999/oauth/token"
    client-id: wamya-mobile-app
    client-secret: S3CR3T
    reset-password-uri: "http://${app.auth-server}:9999/oauth/users/{oAuthId}/do-reset-password"
    
  google-api:
    api-key: AIzaSyD5ZWuXfEdL8BGnQ4lW4cziV1I5uFl6oFQ
    distance-matrix-api:
      url: "https://maps.googleapis.com/maps/api/distancematrix/json?origins={origins}&destinations={destinations}&key={key}"
    geo-coding-api:
      url: "https://maps.googleapis.com/maps/api/geocode/json?latlng={latlng}&result_type={result_type}&key={key}&language={language}"
