spring:
  jpa:
    generate-ddl: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          fetch_size: 20
          batch_versioned_data: true
          lob.non_contextual_creation: true
          time_zone: UTC
          
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

log4jdbc:
  trim:
    sql:
      extrablanklines: false
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
             
logging:
  level:
    jdbc:
      sqlonly: fatal
      resultsettable: info
      sqltiming: info
      audit: fatal
      resultset: fatal
      connection: fatal