server.port: 8443

spring.application.name: gateway

server.ssl:
  key-store-type: PKCS12
  key-store: classpath:keystore/edge.p12
  key-store-password: password
  key-alias: localhost

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost
  auth-server: localhost
  
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 30
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 8

ribbon.ServerListRefreshInterval: 30000

ribbon.NFLoadBalancerPingInterval: 5

spring.cloud.gateway.routes:

- id: oauth-server
  uri: lb://auth-server
  predicates:
  - Path=/oauth/**

- id: websocket_route
  uri: lb:ws://wamya-backend
  predicates:
  - Path=/wamya-backend/wamya-ws/**
   
- id: wamya-backend
  uri: lb://wamya-backend
  predicates:
  - Path=/wamya-backend/**
  
- id: eureka-api
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka/api/{segment}
  filters:
  - SetPath=/eureka/{segment}

- id: eureka-web-start
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka/web
  filters:
  - SetPath=/

- id: eureka-web-other
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka/**


  
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: lb://${app.auth-server}:9999/.well-known/jwks.json

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
---
spring.profiles: docker

app:
  eureka-server: eureka
  auth-server: auth-server
  
#spring:
#  cloud:
#    gateway:
#      default-filters:#      -  DedupeResponseHeader=Access-Control-Allow-Method Access-Control-Allow-Origin Access-Control-Request-Headers
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*" 
            
