spring.profiles: docker
spring.profiles.include: default, b2b-rest-docker, messaging-docker, persistence-docker, web-docker, app-docker

app:
  eureka-server: eureka
  eureka-username: u
  eureka-password: p
    
eureka:
  client:
    eureka-connection-idle-timeout-seconds: 4
    service-url:
      default-zone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 30
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 30
       
ribbon.ServerListRefreshInterval: 30000
ribbon.NFLoadBalancerPingInterval: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"


     

