server:
  port: 8080
  error:
    include-stacktrace: never

#some properties configurations
code.generator:
  length: 4

---
server:
  error:
    include-stacktrace: always
spring:
  profiles: development
  devtools:
    remote:
      secret: test
      debug:
        local-port: 8000
  jpa:    generate-ddl: true
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

logging:
  level:
    com.excentria_it.wamya: DEBUG
  
