version: '2.3'

services:
  database:
    image: postgres:12.3-alpine
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wamya_db
      - POSTGRES_USER=wamya
      - POSTGRES_PASSWORD=wamya   
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wamya -p 5432 -d wamya_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  
  wamya:
    build: .
    mem_limit: 512m
    ports:
      - "9090:9090"
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - POSTGRES_DB=wamya_db
      - POSTGRES_USER=wamya
      - POSTGRES_PASSWORD=wamya
      
    entrypoint: ["java", "-Djava.security.egd=file:/dev/./urandom", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9090", "-jar", "/wamya-backend.jar"]
    depends_on:
      database:
        condition: service_healthy 
    
volumes:
  database-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/postgres/database-data'
