front:
  url:
    protocol: http
    host: localhost
    port: 3000
app:
  server.base.url: https://192.168.21.129:8443/wamya-backend
  password.reset:
    request-validity: H3
    purge-cron-expression: 0 */5 * * * *
  rating:
    record:
      creation-cron-expression: 0 */5 * * * *
      limit: 20
    request:
      sending-cron-expression: 0 0 */1 * * *
      revivals: 3