#phone number and email validation code generator properties
code:
  generator:
    length: 4
    
front:
  url:
    protocol: https
    host: localhost
    port: 8443

app:
  password.reset:
    request-validity: H3
    purge-cron-expression: '0 */5 * * * *'