server:
  port: 8080
  servlet: 
    context-path: /wamya-backend
  error:
    include-stacktrace: always
    
app:
  auth-server: auth-server
  
spring:
  mvc.static-path-pattern: /content/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://${app.auth-server}:9595/realms/fretto/protocol/openid-connect/certs"