server:
  port: 8080
  servlet: 
    context-path: /wamya-backend
  error:
    include-stacktrace: always
app:
  auth-server: localhost
  
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${app.auth-server}:9999/.well-known/jwks.json